name: Lint C#

on:
  push:
      branches:
        - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    uses: Iron-Sky-Studios/reusable-workflows/.github/workflows/lint-csharp.yaml@4897c1d50ac4db33bd999bfeb65d14c8720b044d # main
    secrets: inherit
